// Code generated by coz. DO NOT EDIT.
/**
 * Mixins
 * @module mixins
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get cascadeMix () { return _d(require('./cascadeMix')) },
  get cliMix () { return _d(require('./cliMix')) },
  get exportImportMix () { return _d(require('./exportImportMix')) },
  get migrateMix () { return _d(require('./migrateMix')) },
  get refreshMix () { return _d(require('./refreshMix')) },
  get resourceMix () { return _d(require('./resourceMix')) },
}
